### ISSUE TITLE
Processing to delivery  get illegal char on attachments that prevents delivery from opening

### ISSUE THREAD

**Issue by sshipley64** [ePADD/epadd#454] opened 2024-01-05 23:03 UTC
**Describe the bug**
When exporting from processing to delivery in almost every collection,  I get attachments that say there is an illegal char.  If I go back and change the corresponding emails to do not transfer and export again,  it will run. 

05 Jan 14:45:31 Util ERROR -
java.nio.file.InvalidPathException: Illegal char <      > at index 82: data/blobs/4980.President Obama Announces National Fuel Efficiency PolicyU.S. EPA                05_19_2009 03_34 PM
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
        at java.nio.file.Path.resolve(Path.java:516) ~[?:?]
        at gov.loc.repository.bagit.reader.TagFileReader.createFileFromManifest(TagFileReader.java:56) ~[bagit-5.2.0.jar:?]
        at gov.loc.repository.bagit.reader.ManifestReader.readChecksumFileMap(ManifestReader.java:123) ~[bagit-5.2.0.jar:?]
        at gov.loc.repository.bagit.reader.ManifestReader.readManifest(ManifestReader.java:108) ~[bagit-5.2.0.jar:?]
        at gov.loc.repository.bagit.reader.ManifestReader.readAllManifests(ManifestReader.java:63) ~[bagit-5.2.0.jar:?]
        at gov.loc.repository.bagit.reader.BagReader.read(BagReader.java:61) ~[bagit-5.2.0.jar:?]
        at edu.stanford.muse.index.Archive.readArchiveBag(Archive.java:2558) ~[classes/:?]
        at edu.stanford.muse.index.ArchiveReaderWriter.readArchiveIfPresent(ArchiveReaderWriter.java:842) ~[classes/:?]
        at edu.stanford.muse.index.ArchiveReaderWriter.readArchiveIfPresent(ArchiveReaderWriter.java:828) ~[classes/:?]
        at org.apache.jsp.ajax.async.setExportableAssets_jsp._jspService(setExportableAssets_jsp.java:260) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[epadd-standalone.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[epadd-standalone.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466) ~[epadd-standalone.jar:?]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379) ~[epadd-standalone.jar:?]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327) ~[epadd-standalone.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[epadd-standalone.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[epadd-standalone.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[epadd-standalone.jar:?]
        at edu.stanford.muse.webapp.LoggingFilter.doFilter(LoggingFilter.java:26) ~[classes/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[epadd-standalone.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[epadd-standalone.jar:?]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) ~[log4j-web-2.18.0.jar:2.18.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[epadd-standalone.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[epadd-standalone.jar:?]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[epadd-standalone.jar:?]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[epadd-standalone.jar:?]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[epadd-standalone.jar:?]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[epadd-standalone.jar:?]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[epadd-standalone.jar:?]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[epadd-standalone.jar:?]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[epadd-standalone.jar:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[epadd-standalone.jar:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[epadd-standalone.jar:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[epadd-standalone.jar:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[epadd-standalone.jar:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[epadd-standalone.jar:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[epadd-standalone.jar:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[epadd-standalone.jar:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[epadd-standalone.jar:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

java.nio.file.InvalidPathException: Illegal char <      > at index 82: data/blobs/4980.President Obama Announces National Fuel Efficiency PolicyU.S. EPA                05_19_2009 03_34 PM
java.nio.file.InvalidPathException: Illegal char <      > at index 82: data/blobs/4980.President Obama Announces National Fuel Efficiency PolicyU.S. EPA                05_19_2009 03_34 PM
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.resolve(Path.java:516)
        at gov.loc.repository.bagit.reader.TagFileReader.createFileFromManifest(TagFileReader.java:56)
        at gov.loc.repository.bagit.reader.ManifestReader.readChecksumFileMap(ManifestReader.java:123)
        at gov.loc.repository.bagit.reader.ManifestReader.readManifest(ManifestReader.java:108)
        at gov.loc.repository.bagit.reader.ManifestReader.readAllManifests(ManifestReader.java:63)
        at gov.loc.repository.bagit.reader.BagReader.read(BagReader.java:61)
        at edu.stanford.muse.index.Archive.readArchiveBag(Archive.java:2558)
        at edu.stanford.muse.index.ArchiveReaderWriter.readArchiveIfPresent(ArchiveReaderWriter.java:842)
        at edu.stanford.muse.index.ArchiveReaderWriter.readArchiveIfPresent(ArchiveReaderWriter.java:828)
        at org.apache.jsp.ajax.async.setExportableAssets_jsp._jspService(setExportableAssets_jsp.java:260)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at edu.stanford.muse.webapp.LoggingFilter.doFilter(LoggingFilter.java:26)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:1623)

**To Reproduce**
Export processing module
Go to collection
Click enter 
Get the error below. 

**Expected behavior**

**Screenshots**
![image](https://github.com/ePADD/epadd/assets/10080940/07e95237-f66c-444f-845c-9c75701ae2df)

**Desktop (please complete the following information):**
 - OS: Linux and Windows
 - Browser Chrome and firefox
 - ePADD Version ePADD version Release 10.0.6
 - Java Version jdk-20.0.1

**Additional context**

**Comment by sshipley64** [comment] 2024-01-10 00:34
Okay,  so this is an issue going from epadd processed on Ubuntu and exported and then loaded onto a Windows machine.   It doesn't give this same error loading the delivery module on the same ubuntu that it is processed on.

**Comment by jfarwer** [comment] 2024-01-17 18:11
Just for my understanding: 

Are these the steps you are doing:

- Export from processing to delivery on Ubuntu.

- Copy the exported archive to a Windows machine to the directory epadd-delivery
 
- Start ePADD in delivery mode on the Windows machine which gives the error

?

Many thanks

**Comment by sshipley64** [comment] 2024-01-17 18:14
Yes.  That’s correct.   It didn’t happen when processing and exporting to delivery on windows.

**Comment by jfarwer** [comment] 2024-01-17 18:48
Thanks. Are you able to share an email file or are they private?

**Comment by sshipley64** [comment] 2024-01-17 18:56
They are public record.  Here’s an email that has an attachment that give that error.

**Comment by jfarwer** [comment] 2024-01-17 19:00
Sorry, I can't see any email. Could you please try again?

**Comment by sshipley64** [comment] 2024-01-17 19:04
[epadd-export-docset-b4865538.txt](https://github.com/ePADD/epadd/files/13967534/epadd-export-docset-b4865538.txt)
It doesn't support mboxes,  so I changed to a .txt file.

**Comment by jfarwer** [comment] 2024-01-17 19:09
Great, thanks.

**Comment by jfarwer** [comment] 2024-01-18 16:54
Interesting. The attachment name has a blank as the last character. When importing this email in appraisal on Windows, the file name is not accepted and the attachment is not read. The label 'Error in attachment' is added to the email and a note that there was an error is added to the report.

On Ubuntu, however, a blank as the last character of a file name is no problem. No error occurs, and the attachment is read like any other attachment. An entry with the path and name of the attachment is added to the bag (manifest-sha256.txt). 

When reading that bag file on Windows the blank at the end of the filename causes the exception you are seeing.  

A blank at the end is not an illegal file name but can cause different problems. 

If you try to rename a file in the Windows file explorer, the new name containing for example an '*', it will complain that this is an illegal character. If you try to use a file name ending in a blank it will just remove the blank.

We are thinking about what ePADD should do when encountering such file names. Maybe the best option is just to remove the blank (Do we have to record that change somewhere?).

Please let me know if you have any thoughts on this.

**Comment by sshipley64** [comment] 2024-01-22 16:55
removing that blank space would work for me--I don't particularly see any need to record it.  It would be nice to have that done both in the accession module and in the processing module as it exports.

**Comment by jfarwer** [comment] 2024-01-23 00:23
Thanks. A new version of ePADD with some new features will be released soon. It will also contain the fix for the filenames. When importing emails in appraisal, it removes any blanks at the end of file names. So, the issue is fixed at the first step, and everything works as usual when going to processing and delivery. Fixing the filenames of attachments already imported would be a more complicated operation, so filenames in an existing archive will stay the same when using the new version of ePADD.

I hope that helps. Please let me know if you think anything else is needed.

**Comment by sshipley64** [comment] 2024-01-23 00:26
Thanks.  Darn though.   I have a collection of over 700,000 emails that were already processed in the linux version that I’ll need to deliver on a windows machine.  For some reason our windows machine couldn’t handle a collection that big.  I guess that will have to be redone.

**Comment by jfarwer** [comment] 2024-01-23 14:37
I see. I will think about whether it might be possible to keep working with the existing archive.

Do you know what the problem with importing the large collection was on Windows?

**Comment by sshipley64** [comment] 2024-01-23 16:08
It would crash after a while and just refuse to load more imports without crashing each time. Same ram as Linux.  Same memory given to Java to use.
________________________________

**Comment by sshipley64** [comment] 2024-01-23 17:30
There might also be people who have this error  who won’t know about it and then discover it when they try to move their delivery folders to windows….

**Comment by sshipley64** [comment] 2024-03-05 00:26
I just tried Release 11.0.1-alpha and I'm still getting an illegal char error       

at java.lang.Thread.run(Thread.java:1623) ~[?:?]

java.nio.file.InvalidPathException: Illegal char <      > at index 82: data/blobs/5846.Fwd_ Station Area Planning Community Workshop_  5th _ Bell, 2nd _        Pike and 2nd_ Madison Stations
java.nio.file.InvalidPathException: Illegal char <      > at index 82: data/blobs/5846.Fwd_ Station Area Planning Community Workshop_  5th _ Bell, 2nd _        Pike and 2nd_ Madison Stations

I get an error trying to download the mbox for the email so I can't attach it.

**Comment by jfarwer** [comment] 2024-03-05 17:49
What error do you get when trying to attach the mbox file?

Is this again when trying to load an archive on Windows which has been created on Ubuntu?

Thanks

**Comment by sshipley64** [comment] 2024-03-05 18:58
No,  this is on ubuntu--I can't download the mbox for that message or even download the attachment without getting an error that it won't download.  I have attached the attachment straight from the blob folder.  
[5846.Fwd_ Station Area Planning Community Workshop_  5th _ Bell, 2nd _ Pike and 2nd_ Madison Stations.txt](https://github.com/ePADD/epadd/files/14500089/5846.Fwd_.Station.Area.Planning.Community.Workshop_.5th._.Bell.2nd._.Pike.and.2nd_.Madison.Stations.txt)

**Comment by sshipley64** [comment] 2024-03-05 18:59
I added the txt file extension--it's a forwarded email that it couldn't recognize as an email.

**Comment by jfarwer** [comment] 2024-03-05 19:22
Thanks. So the error occurs when you are trying to import that mbox file? 

Can you send the files epadd.log and epadd.warnings.log from the epadd-settings folder?

**Comment by sshipley64** [comment] 2024-03-05 20:01
Sorry,  I'm not explaining right.  The first error is the same illegal char after moving from linux to windows.   There is also a second error in linux when trying to download the email as an mbox--it just won't do it.   The attachment itself is not exactly an error but it's an attached  forwarded email that is not decoded but still looks to be in base64 for some reason ( i get a pretty good number of these in older collections).  Attached are log and warnings log
[epaddubuntu.zip](https://github.com/ePADD/epadd/files/14500626/epaddubuntu.zip)

**Comment by jfarwer** [comment] 2024-03-05 20:22
Thanks. There seems to be indeed some encoding issue. Let me have a look into that.

**Comment by sshipley64** [comment] 2024-03-05 20:24
Let me know if you want the original mbox or pst--it's public record.  It's gone through Novell Groupwise to Outlook before converting to mbox.

**Comment by jfarwer** [comment] 2024-03-05 22:07
Yes please, the mbox would be great.

________________________________

**Comment by sshipley64** [comment] 2024-03-05 22:31
https://drive.google.com/file/d/1S8fYH2HCGj_yZkP0tyGSSbWMFXcHOU7v/view?usp=drive_link
It's zipped here.

**Comment by jfarwer** [comment] 2024-03-06 18:11
Could you please give me permission to access that file?

**Comment by sshipley64** [comment] 2024-03-06 18:45
sorry, should be able to access it now.

**Comment by jfarwer** [comment] 2024-03-07 13:23
Thanks. In the epadd.log.warnings file you sent it complains about encoding in 'Hexa' and '8bit+'. I can't find any emails with encoding 'Hexa' or '8bit+' in the attached set. Are these emails the ones used in the ePADD run with that warning file?

**Comment by sshipley64** [comment] 2024-03-07 16:03
Yes it's the same collection
________________________________

**Comment by jfarwer** [comment] 2024-03-08 16:40
The name of the attached email (Fwd: Station Area Planning Community Workshop: 5th & Bell, 2nd & Pike and 2nd& Madison Stations) contains a tab instead of white spaces. This doesn't work as a filename and on both Ubuntu and Windows ePADD doesn't show the attachment but adds the label 'Error in attachment'. However, creating the archive on Ubuntu and then reading it on Windows results in ePADD crashing. I am not sure why, but I implemented a fix where tabs are replaced with white spaces. Could you please try this out (you can use either file, one is jar, one is a Windows executable):

https://livemanchesterac-my.sharepoint.com/personal/jochen_farwer_manchester_ac_uk/_layouts/15/download.aspx?UniqueId=acf92d9686ee4d1eb4e94a86a034f9d0&e=Qx3Axq

https://livemanchesterac-my.sharepoint.com/:u:/r/personal/jochen_farwer_manchester_ac_uk/Documents/epadd_fix_tabs.exe?csf=1&web=1&e=N3W2Pe)?csf=1&web=1&e=N3W2Pe

**Comment by sshipley64** [comment] 2024-03-11 15:57
clicking on the link I get
Selected user account does not exist in tenant 'The University of Manchester' and cannot access the application '00000003-0000-0ff1-ce00-000000000000' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account.

**Comment by sshipley64** [comment] 2024-03-11 17:09
It worked now.  I'll get back to you soon.

**Comment by sshipley64** [comment] 2024-03-12 17:29
Okay,  I've tried in all the modules and it doesn't seem to having any issues with that attachment anymore--the attachment is still encoded as base64 though.

**Comment by sshipley64** [comment] 2024-03-22 15:41
On its own.

**Comment by jfarwer** [comment] 2024-03-22 17:30
Yes, ePADD saves the attached emails as part of the message they are attached to. They will be included (untouched in base64) as part of the mbox or eml file when you download or 'export for preservation' the parent message. When you download the attachment on its own you get the encoded message which is a string of characters. As you don't have an app on your computer for viewing the decoded content, it will open in a text editor and show that string of characters. You can put that in a decoder like [https://www.base64decode.org/](https://www.base64decode.org/) and get the decoded message.

I keep seeing emails attached as base64. We could decode them in ePADD and then allow the decoded message to be downloaded, which would be more user-friendly. We will think about that.

**Comment by sshipley64** [comment] 2024-03-25 18:14
Thanks.  If I notice it,  I can decode--  it's if researchers are looking through it,  they may think it's just gibberish or if we don't notice it in a large search download we are giving to researchers.  I can put a note in our user guide,  but almost no one actually reads that.

**Comment by jfarwer** [comment] 2024-08-12 11:46
In version 11.0.1 any blanks at the beginning of attachment filenames will be removed and tabs will be replaced with spaces. This process occurs during import. Attachments from emails already in the collection, imported with ePADD versions before 11.0.1 will remain unchanged.

**Closed by jfarwer** 2024-08-12 11:46 UTC

**Comment by sshipley64** [comment] 2024-10-18 21:04
[Share image]

Shipley, Sarah shared a file with you

Here's the document that Shipley, Sarah shared with you.

<https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/EX8eENeVKdNEmBXWwuuXEQsBdYvjP5s57MiJ-Yn8Ezii6Q?e=4%3AuM4dPp>
[icon]  outputandsteps
[permission globe icon]         This link only works for the direct recipients of this message.
Open <https://seattlegov-my.sharepoint.com/:u:/g/personal/sarah_shipley_seattle_gov/EX8eENeVKdNEmBXWwuuXEQsBdYvjP5s57MiJ-Yn8Ezii6Q?e=4%3AuM4dPp>
[cid:6f83f526-f2b4-454b-91bf-dfe17a529204]

This email is generated through City of Seattle's use of Microsoft 365 and may contain content that is controlled by City of Seattle.
