### ISSUE TITLE
Import/Export Addressbook, Lexicon and Labels

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#219] opened 2018-05-18 04:24 UTC
UI for Import Addressbook, Lexicon and Labels  files

**Comment by peterchanws** [comment] 2018-05-21 15:47
Appraisal, Processing, Delivery modules:
"Edit Correspondents" in correspondent browsing page will list to
[Correspondents.pdf](https://github.com/ePADD/epadd/files/2023182/Correspondents.pdf)

**Comment by peterchanws** [comment] 2018-05-21 15:57
Appraisal, Processing, Delivery modules:
Add "Import/Export" to the New Label screen. Click "Import/Export" will take you to
![labels](https://user-images.githubusercontent.com/1050899/40317027-02c11952-5cd5-11e8-80e8-4c77651460fb.png)
![labels - import export](https://user-images.githubusercontent.com/1050899/40317030-05e09f72-5cd5-11e8-9bc4-dc59b258d403.png)

**Comment by peterchanws** [comment] 2018-05-21 16:22
Appraisal, Processing, Delivery modules:
Replace "View/Edit Lexicon" and "Create Ne Lexicon" with "Manage Lexicon".
Click "Manage Lexicon" will take you to

**Comment by peterchanws** [comment] 2018-05-23 22:51
Add "Download" and "Upload" buttons at the bottom of the Edit Lexicon screen.
<img width="1071" alt="screen shot 2018-05-23 at 2 59 21 pm" src="https://user-images.githubusercontent.com/1050899/40455286-26859c6e-5ea1-11e8-9a92-1358900c9019.png">

**Comment by peterchanws** [comment] 2018-05-23 23:21
Add "Upload New Lexicon" next to "Create New Lexicon"
<img width="1056" alt="screen shot 2018-05-23 at 4 18 38 pm" src="https://user-images.githubusercontent.com/1050899/40456267-4a014f36-5ea5-11e8-9e48-1b72779474da.png">

**Comment by peterchanws** [comment] 2018-05-23 23:26
**This part become critical if we cannot find improve the response time to load correspondents in browser for large collections. It took 8 min 25 sec to load the correspondents in the Terry archive.

Add "Download Correspondent File" and "Upload Correspondent File" next to "Edit Correspondents"
<img width="1109" alt="screen shot 2018-05-23 at 4 22 59 pm" src="https://user-images.githubusercontent.com/1050899/40456353-c005bfa0-5ea5-11e8-8021-bedf239a632e.png">

**Comment by peterchanws** [comment] 2018-06-11 23:06
ver 6 beta
export/import correspondent works fine

Export label:
1. new labels not exported unless user click"SAVE" on top before export

Export lexicon: Error

**Comment by chinuhub** [comment] 2018-06-12 03:31
Point 1 is fixed now. Can you send the log for export lexicon error? I couldn't reproduce the error.

**Comment by peterchanws** [comment] 2018-06-12 05:53
I tested export lexicon in my mac at home. It works fine.

**Comment by peterchanws** [comment] 2018-06-12 05:56
Sorry. The error happens only with new lexicon.
[ePADD Log.pdf](https://github.com/ePADD/epadd/files/2092720/ePADD.Log.pdf)

**Comment by peterchanws** [comment] 2018-06-13 15:58
ver epadd-standalone-v6-beta-12June.jar
Label issue fixed
New lexicon export issue fixed.

**Comment by peterchanws** [comment] 2018-06-13 23:12
Uploaded lexicon with same name as existing lexicon do NOT replace existing lexicon.

**Comment by peterchanws** [comment] 2018-06-13 23:52
Sorry, using wrong file. Uploaded lexicon DO replace existing lexicon with same name.

No outstanding issue.

**Comment by peterchanws** [comment] 2018-06-29 22:44
@chinuhub 
Josh remind me what happens to messages with labels which are not in the new file. We need to work on that after the release.

**Comment by peterchanws** [comment] 2018-07-09 16:04
If there is any messages  with existing labels, system will ask users to remove labels from existing messages. Otherwise, system will not proceed.

**Comment by peterchanws** [comment] 2018-07-12 23:35
Feature implemnented

**Closed** 2018-08-01 05:45 UTC
Labels: Tested-Waiting for release, Version 6
