### ISSUE TITLE
Better error messaging when out of memory

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#17] opened 2016-01-15 16:33 UTC
We should have better error messages when we run out of memory.
esp. during mbox parsing (but also in other possible places).
Currently we fail silently with no sign of trouble, except that a small number of messages is indexed.
The error message should be conveyed to the user also, apart from the log file.

**Comment by vihari** [comment] 2016-02-03 12:06
duplicate of #50

**Comment by peterchanws** [comment] 2016-08-10 15:31
ProdPad Idea#45

**Closed by peterchanws** 2016-08-10 15:31 UTC
Labels: Enhancement, Medium priority
