### ISSUE TITLE
Export to Preservation (Processing module) does not complete

### ISSUE THREAD

**Issue by juliewetherill** [ePADD/epadd#444] opened 2023-04-11 18:53 UTC
**Describe the bug**
Preservation exports are working in the Appraisal module but not the Processing module (ePADD v10.0.3). Specifically, it is EML preservation exports that start but never complete. MBOX preservation exports from the Processing module seem to complete normally but the log files contain some of the same FileNotFoundExceptions as the EML export, so I'm not sure those MBOX exports are complete.

**Expected behavior**
When I select the EML format for preservation export, I expect the export to complete in reasonable (time to completion depends on size of the archive) and the export directory should be fully formed.

**Screenshots and more information**
More info in this google doc: https://docs.google.com/document/d/1RJjJVX_51LjyzfpqtrEDJKYJpowhd2V-VavzJtWdw_w/edit?usp=sharing

**Comment by jfarwer** [comment] 2023-04-12 18:17
Thanks for reporting this and for the detailed feedback. If you haven't done this already could you please try a different set of emails (or a subset of the used emails) and let me know whether the problem is the same?

**Comment by jfarwer** [comment] 2023-06-20 16:11
This has been fixed in version 10.0.6.

**Closed by jfarwer** 2023-06-20 16:11 UTC
Labels: Version 10

**Comment by juliewetherill** [comment] 2023-06-21 19:47
Hi Jochen,

Unfortunately, I can’t test the fix for #444. I’m blocked by https://github.com/ePADD/epadd/issues/447 (Error importing accession into Processing module). I’m running 10.0.6 now and bug described in #447 is present there.

Regards. –julie wetherill

**Comment by jfarwer** [comment] 2023-06-26 12:19
Hi,

Do you need to import the archive as an accession into the processing module? Or can you also just copy the archive exported from the appraisal module to the folder `epadd-processing` (so it shows up as an archive when you start epadd in processing mode)?

Many thanks

**Comment by juliewetherill** [comment] 2023-06-26 14:47
Hi Jochen,

I tried it your way. Not quite a ‘copy’ but … from the accessions module, I exported the archive directly to the folder C:\Users\jmw922\epadd-processing, so the end result was:

***@***.***

When I open the processing module, I see this:
***@***.***

When I click the archive title ‘Julie Wetherill’, I see this:
***@***.***

By skipping the ‘Add’ accession step, it seems I lost the chance to assign accession metadata to the archive and also shouldn’t there be a block of accession metadata displaying on the collection landing page? This is the screenshot from User Manual with accession metadata:
***@***.***
I don’t see a way to go back and add accession metadata. I can click ‘Add’ and fill out the accession metadata, but in the end I get the error that there’s a collection with that name already present.

–julie
